### ISSUE TITLE
Purpose of the Film class?

### ISSUE THREAD

**Issue by akshaysmurthy** [Roshanjossey/roshan#1]
In main.py though you have instantiated a `Film` class, you don't seem to be using it anywhere. I see that the plugin classes also do not use objects of this class but instead use a `movie` dictionary that is created in main.py

**Comment by Roshanjossey** [comment]
In previous versions, plugins used instances of film class to get data. But I found this to be a bad design because there won't be much decoupling film class and plugin classes. So I changed it.
But at the end, it didn't do much good, plugins depend on dictionary defined in main.py

**Comment by akshaysmurthy** [comment]
The current implementation is better I think.
