### ISSUE TITLE
Coupling in the plugin classes

### ISSUE THREAD

**Issue by akshaysmurthy** [Roshanjossey/roshan#3]
The plugin classes are quite dependent on the concretions of the `movie` dictionary. Eg., For a change as small as changing an attribute name (Eg., Rename `name` to `title`), all the plugin classes have to be modified. Think of plugins as developed by third parties. Changes to the main app code should not ideally require them to change their code :)

**Comment by Roshanjossey** [comment]
Yes this is definitely a big problem. I'm thinking about fixing this problem and issue #1 at the same time. Please give me some time

**Comment by Roshanjossey** [comment]
I've attempted to make the classes loosely coupled.
I've used film class as a mediator between main and export classes ( Trying to resolve issue #1  )
Now Export doesn't need to know what data is provided.
Export classes(plugins) just call provide_values method of film class and gets an ordered dictionary as return value
export function is now just iterating through the dictionary obtained and exporting them to required format

Is plugins not knowing what data they are dealing with, a good design?
Please provide pointers and suggestions.

**Comment by akshaysmurthy** [comment]
Please give me until the evening to get back to you on this and the other issues :)

**Comment by akshaysmurthy** [comment]
Yes. It is a good design because a plugin class now conforms to the Single Responsibility Principle. And by making it dependent on an abstraction like `provide_values` it also conforms to the Dependendency Inversion principle. We can talk more about this soon :)
